/* eslint-disable prettier/prettier */
const verbs = [
    {
    'Base': 'arise',
    'Hungarian': 'felmerül',
    'Past-simple': 'arose',
    'Past-Participle': 'arisen',
    },
    {
    'Base': 'awake',
    'Hungarian': 'ébred',
    'Past-simple': 'awoke',
    'Past-Participle': 'awoken',
    },
    {
    'Base': 'be',
    'Hungarian': 'lenni',
    'Past-simple': 'was/were',
    'Past-Participle': 'been',
    },
    {
    'Base': 'bear',
    'Hungarian': 'hord',
    'Past-simple': 'bore',
    'Past-Participle': 'born(e)',
    },
    {
    'Base': 'beat',
    'Hungarian': 'ver',
    'Past-simple': 'beat',
    'Past-Participle': 'beaten',
    },
    {
    'Base': 'become',
    'Hungarian': 'válik',
    'Past-simple': 'became',
    'Past-Participle': 'become',
    },
    {
    'Base': 'begin',
    'Hungarian': 'elkezd',
    'Past-simple': 'began',
    'Past-Participle': 'begun',
    },
    {
    'Base': 'bend',
    'Hungarian': 'hajlik',
    'Past-simple': 'bent',
    'Past-Participle': 'bent',
    },
    {
    'Base': 'bet',
    'Hungarian': 'fogad',
    'Past-simple': 'bet',
    'Past-Participle': 'bet',
    },
    {
    'Base': 'bind',
    'Hungarian': 'köt',
    'Past-simple': 'bound',
    'Past-Participle': 'bound',
    },
    {
    'Base': 'bite',
    'Hungarian': 'harap',
    'Past-simple': 'bit',
    'Past-Participle': 'bitten',
    },
    {
    'Base': 'bleed',
    'Hungarian': 'vérezik',
    'Past-simple': 'bled',
    'Past-Participle': 'bled',
    },
    {
    'Base': 'blow',
    'Hungarian': 'fúj',
    'Past-simple': 'blew',
    'Past-Participle': 'blown',
    },
    {
    'Base': 'break',
    'Hungarian': 'tör',
    'Past-simple': 'broke',
    'Past-Participle': 'broken',
    },
    {
    'Base': 'breed',
    'Hungarian': 'szaporodik',
    'Past-simple': 'bred',
    'Past-Participle': 'bred',
    },
    {
    'Base': 'bring',
    'Hungarian': 'hoz',
    'Past-simple': 'brought',
    'Past-Participle': 'brought',
    },
    {
    'Base': 'broadcast',
    'Hungarian': 'közvetít',
    'Past-simple': 'broadcast',
    'Past-Participle': 'broadcast',
    },
    {
    'Base': 'build',
    'Hungarian': 'épít',
    'Past-simple': 'built',
    'Past-Participle': 'built',
    },
    {
    'Base': 'burn',
    'Hungarian': 'ég/éget',
    'Past-simple': 'burnt/burned',
    'Past-Participle': 'burnt/burned',
    },
    {
    'Base': 'burst',
    'Hungarian': 'szakad',
    'Past-simple': 'burst',
    'Past-Participle': 'burst',
    },
    {
    'Base': 'buy',
    'Hungarian': 'vesz',
    'Past-simple': 'bought',
    'Past-Participle': 'bought',
    },
    {
    'Base': 'can',
    'Hungarian': 'képes',
    'Past-simple': 'could',
    'Past-Participle': 'been able',
    },
    {
    'Base': 'catch',
    'Hungarian': 'fog',
    'Past-simple': 'caught',
    'Past-Participle': 'caught',
    },
    {
    'Base': 'choose',
    'Hungarian': 'választ',
    'Past-simple': 'chose',
    'Past-Participle': 'chosen',
    },
    {
    'Base': 'cling',
    'Hungarian': 'ragaszkodik',
    'Past-simple': 'clung',
    'Past-Participle': 'clung',
    },
    {
    'Base': 'come',
    'Hungarian': 'jön',
    'Past-simple': 'came',
    'Past-Participle': 'come',
    },
    {
    'Base': 'cost',
    'Hungarian': 'kerül',
    'Past-simple': 'cost',
    'Past-Participle': 'cost',
    },
    {
    'Base': 'creep',
    'Hungarian': 'kúszik',
    'Past-simple': 'crept',
    'Past-Participle': 'crept',
    },
    {
    'Base': 'cut',
    'Hungarian': 'vág',
    'Past-simple': 'cut',
    'Past-Participle': 'cut',
    },
    {
    'Base': 'deal',
    'Hungarian': 'kezel',
    'Past-simple': 'dealt',
    'Past-Participle': 'dealt',
    },
    {
    'Base': 'dig',
    'Hungarian': 'ás',
    'Past-simple': 'dug',
    'Past-Participle': 'dug',
    },
    {
    'Base': 'do',
    'Hungarian': 'csinál',
    'Past-simple': 'did',
    'Past-Participle': 'done',
    },
    {
    'Base': 'draw',
    'Hungarian': 'rajzol',
    'Past-simple': 'drew',
    'Past-Participle': 'drawn',
    },
    {
    'Base': 'dream',
    'Hungarian': 'álmodik',
    'Past-simple': 'dreamt/dreamed',
    'Past-Participle': 'dreamt/dreamed',
    },
    {
    'Base': 'drink',
    'Hungarian': 'iszik',
    'Past-simple': 'drank',
    'Past-Participle': 'drunk',
    },
    {
    'Base': 'drive',
    'Hungarian': 'vezet',
    'Past-simple': 'drove',
    'Past-Participle': 'driven',
    },
    {
    'Base': 'eat',
    'Hungarian': 'eszik',
    'Past-simple': 'ate',
    'Past-Participle': 'eaten',
    },
    {
    'Base': 'fall',
    'Hungarian': 'esik',
    'Past-simple': 'fell',
    'Past-Participle': 'fallen',
    },
    {
    'Base': 'feed',
    'Hungarian': 'etet',
    'Past-simple': 'fed',
    'Past-Participle': 'fed',
    },
    {
    'Base': 'feel',
    'Hungarian': 'érez',
    'Past-simple': 'felt',
    'Past-Participle': 'felt',
    },
    {
    'Base': 'fight',
    'Hungarian': 'harcol',
    'Past-simple': 'fought',
    'Past-Participle': 'fought',
    },
    {
    'Base': 'find',
    'Hungarian': 'talál',
    'Past-simple': 'found',
    'Past-Participle': 'found',
    },
    {
    'Base': 'fly',
    'Hungarian': 'repül',
    'Past-simple': 'flew',
    'Past-Participle': 'flown',
    },
    {
    'Base': 'forbid',
    'Hungarian': 'megtilt',
    'Past-simple': 'forbade',
    'Past-Participle': 'forbidden',
    },
    {
    'Base': 'forget',
    'Hungarian': 'elfelejt',
    'Past-simple': 'forgot',
    'Past-Participle': 'forgotten',
    },
    {
    'Base': 'forgive',
    'Hungarian': 'megbocsát',
    'Past-simple': 'forgave',
    'Past-Participle': 'forgiven',
    },
    {
    'Base': 'freeze',
    'Hungarian': 'megfagy',
    'Past-simple': 'froze',
    'Past-Participle': 'frozen',
    },
    {
    'Base': 'get',
    'Hungarian': 'kap',
    'Past-simple': 'got',
    'Past-Participle': 'got',
    },
    {
    'Base': 'give',
    'Hungarian': 'ad',
    'Past-simple': 'gave',
    'Past-Participle': 'given',
    },
    {
    'Base': 'go',
    'Hungarian': 'megy',
    'Past-simple': 'went',
    'Past-Participle': 'gone',
    },
    {
    'Base': 'grind',
    'Hungarian': 'őröl',
    'Past-simple': 'ground',
    'Past-Participle': 'ground',
    },
    {
    'Base': 'grow',
    'Hungarian': 'nő',
    'Past-simple': 'grew',
    'Past-Participle': 'grown',
    },
    {
    'Base': 'hang',
    'Hungarian': 'akaszt',
    'Past-simple': 'hung',
    'Past-Participle': 'hung',
    },
    {
    'Base': 'have',
    'Hungarian': 'van',
    'Past-simple': 'had',
    'Past-Participle': 'had',
    },
    {
    'Base': 'hear',
    'Hungarian': 'hall',
    'Past-simple': 'heard',
    'Past-Participle': 'heard',
    },
    {
    'Base': 'hide',
    'Hungarian': 'elrejt',
    'Past-simple': 'hid',
    'Past-Participle': 'hidden',
    },
    {
    'Base': 'hit',
    'Hungarian': 'üt',
    'Past-simple': 'hit',
    'Past-Participle': 'hit',
    },
    {
    'Base': 'hold',
    'Hungarian': 'tart',
    'Past-simple': 'held',
    'Past-Participle': 'held',
    },
    {
    'Base': 'hurt',
    'Hungarian': 'megsért',
    'Past-simple': 'hurt',
    'Past-Participle': 'hurt',
    },
    {
    'Base': 'keep',
    'Hungarian': 'tart',
    'Past-simple': 'kept',
    'Past-Participle': 'kept',
    },
    {
    'Base': 'kneel',
    'Hungarian': 'guggol',
    'Past-simple': 'knelt',
    'Past-Participle': 'knelt',
    },
    {
    'Base': 'know',
    'Hungarian': 'tud',
    'Past-simple': 'knew',
    'Past-Participle': 'known',
    },
    {
    'Base': 'lay',
    'Hungarian': 'lehelyez',
    'Past-simple': 'laid',
    'Past-Participle': 'laid',
    },
    {
    'Base': 'lead',
    'Hungarian': 'vezet',
    'Past-simple': 'led',
    'Past-Participle': 'led',
    },
    {
    'Base': 'lean',
    'Hungarian': 'dől',
    'Past-simple': 'leant/leaned',
    'Past-Participle': 'leant/leaned',
    },
    {
    'Base': 'learn',
    'Hungarian': 'tanul',
    'Past-simple': 'learnt/learned',
    'Past-Participle': 'learnt/learned',
    },
    {
    'Base': 'leave',
    'Hungarian': 'elhagy',
    'Past-simple': 'left',
    'Past-Participle': 'left',
    },
    {
    'Base': 'lent',
    'Hungarian': 'kölcsönad',
    'Past-simple': 'lent',
    'Past-Participle': 'lent',
    },
    {
    'Base': 'lie(in bed)',
    'Hungarian': 'fekszik',
    'Past-simple': 'lay',
    'Past-Participle': 'lain',
    },
    {
    'Base': 'lie',
    'Hungarian': 'hazudik',
    'Past-simple': 'lied',
    'Past-Participle': 'lied',
    },
    {
    'Base': 'light',
    'Hungarian': 'meggyújt',
    'Past-simple': 'lit/lighted',
    'Past-Participle': 'lit/lighted',
    },
    {
    'Base': 'lose',
    'Hungarian': 'elveszít',
    'Past-simple': 'lost',
    'Past-Participle': 'lost',
    },
    {
    'Base': 'make',
    'Hungarian': 'készít',
    'Past-simple': 'made',
    'Past-Participle': 'made',
    },
    {
    'Base': 'may',
    'Past-simple': 'might',
    'Past-Participle': '-',
    'Hungarian': 'lehetséges',
    },
    {
    'Base': 'mean',
    'Past-simple': 'meant',
    'Past-Participle': 'meant',
    'Hungarian': 'jelent',
    },
    {
    'Base': 'meet',
    'Past-simple': 'met',
    'Past-Participle': 'met',
    'Hungarian': 'találkozik',
    },
    {
    'Base': 'mow',
    'Past-simple': 'mowed',
    'Past-Participle': 'mown/mowed',
    'Hungarian': 'nyír',
    },
    {
    'Base': 'must',
    'Past-simple': 'had to',
    'Past-Participle': '-',
    'Hungarian': 'kell',
    },
    {
    'Base': 'overtake',
    'Past-simple': 'overtook',
    'Past-Participle': 'overtaken',
    'Hungarian': 'megelőz',
    },
    {
    'Base': 'pay',
    'Past-simple': 'paid',
    'Past-Participle': 'paid',
    'Hungarian': 'fizet',
    },
    {
    'Base': 'put',
    'Past-simple': 'put',
    'Past-Participle': 'put',
    'Hungarian': 'tesz',
    },
    {
    'Base': 'read',
    'Past-simple': 'read',
    'Past-Participle': 'read',
    'Hungarian': 'olvas',
    },
    {
    'Base': 'ride',
    'Past-simple': 'rode',
    'Past-Participle': 'ridden',
    'Hungarian': 'lovagol',
    },
    {
    'Base': 'ring',
    'Past-simple': 'rang',
    'Past-Participle': 'rung',
    'Hungarian': 'csenget',
    },
    {
    'Base': 'rise',
    'Past-simple': 'rose',
    'Past-Participle': 'risen',
    'Hungarian': 'felkel',
    },
    {
    'Base': 'run',
    'Past-simple': 'ran',
    'Past-Participle': 'run',
    'Hungarian': 'fut',
    },
    {
    'Base': 'saw',
    'Past-simple': 'sawed',
    'Past-Participle': 'sawn/sawed',
    'Hungarian': 'fűrészel',
    },
    {
    'Base': 'say',
    'Past-simple': 'said',
    'Past-Participle': 'said',
    'Hungarian': 'mond',
    },
    {
    'Base': 'see',
    'Past-simple': 'saw',
    'Past-Participle': 'seen',
    'Hungarian': 'lát',
    },
    {
    'Base': 'sell',
    'Past-simple': 'sold',
    'Past-Participle': 'sold',
    'Hungarian': 'elad',
    },
    {
    'Base': 'send',
    'Past-simple': 'sent',
    'Past-Participle': 'sent',
    'Hungarian': 'küld',
    },
    {
    'Base': 'set',
    'Past-simple': 'set',
    'Past-Participle': 'set',
    'Hungarian': 'beállít',
    },
    {
    'Base': 'sew',
    'Past-simple': 'sewed',
    'Past-Participle': 'sewn/sewed',
    'Hungarian': 'varr',
    },
    {
    'Base': 'shake',
    'Past-simple': 'shook',
    'Past-Participle': 'shaken',
    'Hungarian': 'ráz',
    },
    {
    'Base': 'shall',
    'Past-simple': 'should',
    'Past-Participle': '-',
    'Hungarian': 'kellene',
    },
    {
    'Base': 'shed',
    'Past-simple': 'shed',
    'Past-Participle': 'shed',
    'Hungarian': 'ont',
    },
    {
    'Base': 'shine',
    'Past-simple': 'shone',
    'Past-Participle': 'shone',
    'Hungarian': 'ragyog',
    },
    {
    'Base': 'shoot',
    'Past-simple': 'shot',
    'Past-Participle': 'shot',
    'Hungarian': 'lő',
    },
    {
    'Base': 'show',
    'Past-simple': 'showed',
    'Past-Participle': 'shown',
    'Hungarian': 'mutat',
    },
    {
    'Base': 'shrink',
    'Past-simple': 'shrank',
    'Past-Participle': 'shrunk',
    'Hungarian': 'zsugorodik',
    },
    {
    'Base': 'shut',
    'Past-simple': 'shut',
    'Past-Participle': 'shut',
    'Hungarian': 'becsuk',
    },
    {
    'Base': 'sing',
    'Past-simple': 'sang',
    'Past-Participle': 'sung',
    'Hungarian': 'énekel',
    },
    {
    'Base': 'sink',
    'Past-simple': 'sank',
    'Past-Participle': 'sunk',
    'Hungarian': 'süllyed',
    },
    {
    'Base': 'sit',
    'Past-simple': 'sat',
    'Past-Participle': 'sat',
    'Hungarian': 'ül',
    },
    {
    'Base': 'sleep',
    'Past-simple': 'slept',
    'Past-Participle': 'slept',
    'Hungarian': 'alszik',
    },
    {
    'Base': 'slide',
    'Past-simple': 'slid',
    'Past-Participle': 'slid',
    'Hungarian': 'csúszik',
    },
    {
    'Base': 'smell',
    'Past-simple': 'smelt',
    'Past-Participle': 'smelt',
    'Hungarian': 'szagol',
    },
    {
    'Base': 'sow',
    'Past-simple': 'sowed',
    'Past-Participle': 'sown/sowed',
    'Hungarian': 'vet',
    },
    {
    'Base': 'speak',
    'Past-simple': 'spoke',
    'Past-Participle': 'spoken',
    'Hungarian': 'beszél',
    },
    {
    'Base': 'spell',
    'Past-simple': 'spelt/spelled',
    'Past-Participle': 'spelt/spelled',
    'Hungarian': 'betűz',
    },
    {
    'Base': 'spend',
    'Past-simple': 'spent',
    'Past-Participle': 'spent',
    'Hungarian': 'költ',
    },
    {
    'Base': 'spill',
    'Past-simple': 'spilt/spilled',
    'Past-Participle': 'spilt/spilled',
    'Hungarian': 'kiönt',
    },
    {
    'Base': 'spit',
    'Past-simple': 'spat',
    'Past-Participle': 'spat',
    'Hungarian': 'köp',
    },
    {
    'Base': 'spread',
    'Past-simple': 'spread',
    'Past-Participle': 'spread',
    'Hungarian': 'terjed',
    },
    {
    'Base': 'stand',
    'Past-simple': 'stood',
    'Past-Participle': 'stood',
    'Hungarian': 'áll',
    },
    {
    'Base': 'steal',
    'Past-simple': 'stole',
    'Past-Participle': 'stolen',
    'Hungarian': 'lop',
    },
    {
    'Base': 'stick',
    'Past-simple': 'stuck',
    'Past-Participle': 'stuck',
    'Hungarian': 'ragad',
    },
    {
    'Base': 'sting',
    'Past-simple': 'stung',
    'Past-Participle': 'stung',
    'Hungarian': 'szúr',
    },
    {
    'Base': 'stink',
    'Past-simple': 'stank',
    'Past-Participle': 'stunk',
    'Hungarian': 'büdös',
    },
    {
    'Base': 'strike',
    'Past-simple': 'struck',
    'Past-Participle': 'struck',
    'Hungarian': 'lecsapás',
    },
    {
    'Base': 'swear',
    'Past-simple': 'swore',
    'Past-Participle': 'sworn',
    'Hungarian': 'esküszik',
    },
    {
    'Base': 'sweep',
    'Past-simple': 'swept',
    'Past-Participle': 'swept',
    'Hungarian': 'söpör',
    },
    {
    'Base': 'swell',
    'Past-simple': 'swelled',
    'Past-Participle': 'swollen/swelled',
    'Hungarian': 'duzzad',
    },
    {
    'Base': 'swim',
    'Past-simple': 'swam',
    'Past-Participle': 'swum',
    'Hungarian': 'úszik',
    },
    {
    'Base': 'swing',
    'Past-simple': 'swung',
    'Past-Participle': 'swung',
    'Hungarian': 'hintázik',
    },
    {
    'Base': 'take',
    'Past-simple': 'took',
    'Past-Participle': 'taken',
    'Hungarian': 'fog',
    },
    {
    'Base': 'teach',
    'Past-simple': 'taught',
    'Past-Participle': 'taught',
    'Hungarian': 'tanít',
    },
    {
    'Base': 'tear',
    'Past-simple': 'tore',
    'Past-Participle': 'torn',
    'Hungarian': 'szakít',
    },
    {
    'Base': 'tell',
    'Past-simple': 'told',
    'Past-Participle': 'told',
    'Hungarian': 'mond',
    },
    {
    'Base': 'think',
    'Past-simple': 'thought',
    'Past-Participle': 'thought',
    'Hungarian': 'gondol',
    },
    {
    'Base': 'throw',
    'Past-simple': 'threw',
    'Past-Participle': 'thrown',
    'Hungarian': 'dob',
    },
    {
    'Base': 'understand',
    'Past-simple': 'understood',
    'Past-Participle': 'understood',
    'Hungarian': 'megért',
    },
    {
    'Base': 'wake',
    'Past-simple': 'woke',
    'Past-Participle': 'woken',
    'Hungarian': 'felébred',
    },
    {
    'Base': 'wear',
    'Past-simple': 'wore',
    'Past-Participle': 'worn',
    'Hungarian': 'visel',
    },
    {
    'Base': 'weep',
    'Past-simple': 'wept',
    'Past-Participle': 'wept',
    'Hungarian': 'sír',
    },
    {
    'Base': 'will',
    'Past-simple': 'would',
    'Past-Participle': '-',
    'Hungarian': 'akar',
    },
    {
    'Base': 'win',
    'Past-simple': 'won',
    'Past-Participle': 'won',
    'Hungarian': 'nyer',
    },
    {
    'Base': 'wind',
    'Past-simple': 'wound',
    'Past-Participle': 'wound',
    'Hungarian': 'teker',
    },
    {
    'Base': 'write',
    'Past-simple': 'wrote',
    'Past-Participle': 'written',
    'Hungarian': 'ír',
    }
]

export default verbs